### PR TITLE
fix(text-minimessage): Properly handle escaped tag opens

### LINKED ISSUE #821: escapeTags doesnt works correctly
I'm using `miniMessage.deserialize(miniMessage.escapeTags(playerChatEvent.getMessage()))` but when i use `<<aqua> a` it will escape tags but not correctly 
image

WIth `<agua> a` it works fine:
image

### PR DESCRIPTION
**Pull request by zml2008**
Fixes GH-821

### CODE REVIEW

File: text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/internal/parser/Token.java [hunk 1]
```diff
@@ -126,6 +127,19 @@ public CharSequence get(final CharSequence message) {
     );
   }
 
+  @Override
+  public boolean equals(final Object other) {
```
Comment (rymiel) [inline text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/internal/parser/Token.java:131]: This is just used for tests, yes?

Comment (zml2008) [reply text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/internal/parser/Token.java:131]: yeah, so we can directly compare token output

**Review by rymiel — APPROVED** [review]
idk i can't find any flaws
