### PR TITLE
bug(#788): disable html escaping and use uppercase hex colour codes

### LINKED ISSUE #788: Component serialization doesn't match vanilla
Some components when serialized doesn't match vanilla's string represantation which causes issues with server side signature validation. Example of a difference:
Adventure:
```json
{"extra":[{"color":"#ff00ff","text":"PREPEND\u003e"},{"text":"/sign test"},{"color":"#ff00ff","text":"\u003cAPPEND"}],"text":""}
```
Minecraft:
```json
{"extra":[{"color":"#FF00FF","text":"PREPEND>"},{"text":"/sign test"},{"color":"#FF00FF","text":"<APPEND"}],"text":""}
```

### PR DESCRIPTION
**Pull request by kashike**

### CODE REVIEW

**Review by kezz — APPROVED** [review]

File: text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/TextColorSerializer.java [hunk 1]
```diff
@@ -49,10 +49,14 @@ public void write(final JsonWriter out, final TextColor value) throws IOExceptio
     } else if (this.downsampleColor) {
       out.value(NamedTextColor.NAMES.key(NamedTextColor.nearestTo(value)));
     } else {
-      out.value(value.asHexString());
+      out.value(asUpperCaseHexString(value));
     }
   }
 
+  private static String asUpperCaseHexString(final TextColor color) {
+    return String.format("#%06X", color.value()); // to be consistent with vanilla
```
Comment (zml2008) [inline text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/TextColorSerializer.java]:
```suggestion
    return String.format(Locale.ROOT, "#%06X", color.value()); // to be consistent with vanilla
```

just in case number formatting is locale-dependent

**Review by zml2008 — CHANGES_REQUESTED** [review]

**Review by zml2008 — APPROVED** [review]
