### PR TITLE
fix(key): fix combined namespace+value pattern + extract to own annotations

### LINKED ISSUE #919: Key is parsable despite documented otherwise
String `:my_key` is parsable into `minecraft:my_key`, but it doesn't follow the documented pattern [`([a-z0-9_\\-.]+:)?[a-z0-9_\\-./]+`](https://jd.advntr.dev/key/4.13.1/net/kyori/adventure/key/Key.html#key(java.lang.String)) - the pattern requires at least one symbol for the namespace if such is used.

### PR DESCRIPTION
**Pull request by kashike**

### CODE REVIEW

**Review by zml2008 — APPROVED** [review]

File: key/src/main/java/net/kyori/adventure/key/KeyPattern.java [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+import java.lang.annotation.Retention;
+import java.lang.annotation.RetentionPolicy;
+import java.lang.annotation.Target;
+import org.intellij.lang.annotations.Pattern;
+
+@Documented
+@Pattern("(?:(" + KeyImpl.NAMESPACE_PATTERN + ":)?|:)" + KeyImpl.VALUE_PATTERN)
+@Retention(RetentionPolicy.CLASS)
+@Target({ElementType.FIELD, ElementType.LOCAL_VARIABLE, ElementType.METHOD, ElementType.PARAMETER})
+@interface KeyPattern {
```
Comment (zml2008) [inline key/src/main/java/net/kyori/adventure/key/KeyPattern.java:37]: Do we want this to be public? or is package-private fine?
