### PR TITLE
fix(api): add missing ScopedComponent overrides

### LINKED ISSUE #1154: ScopedComponent doesn't always respect initial component type
While messing around with some components, an issue arose when using `Component#font(Key)` on its own outside of builders. It doesn't respect the initial provided component type in it's returned output.

Image

<details>
<summary> EDIT: after a bit more messing around these are all the effected methods</summary>

`ScopedComponent#font(Key)`,
`ScopedComponent#style(Consumer<Builder>, Strategy)`,
`ScopedComponent#appendNewLine()`,
`ScopedComponent#appendSpace()`,
`ScopedComponent#applyFallbackStyle(StyleBuilderApplicable...)`,
`ScopedComponent#applyFallbackStyle(Style)`,
`ScopedComponent#decorate(TextDecoration....)`,
`ScopedComponent#decorateIfAbsent(TextDecoration, TextDecoration$State)`,
`ScopedComponent#decorations(Set<TextDecoration>, boolean)`,
`ScopedComponent#decorations(Map<TextDecoration, TextDecoration$State>)`,
`ScopedComponent#replaceText(Consumer<Builder>)`, and
`ScopedComponent#replaceText(TextReplacementConfig)`

I've left out the `#compact` method since just like `#asComponent` it seems more intentional design wise for it to be `Component`

</details>

### PR DESCRIPTION
**Pull request by zml2008**
Fixes GH-1154

### CODE REVIEW

File: api/src/main/java/net/kyori/adventure/text/ScopedComponent.java [hunk 1]
```diff
@@ -155,4 +206,22 @@ public interface ScopedComponent<C extends Component> extends Component {
...
+  @SuppressWarnings("unchecked")
+  default @NotNull C replaceText(final @NotNull Consumer<TextReplacementConfig.Builder> configurer) {
+    return (C) Component.super.replaceText(configurer);
+  }
+
+  @Override
+  @SuppressWarnings("unchecked")
+  default @NotNull C replaceText(final @NotNull TextReplacementConfig config) {
+    return (C) Component.super.replaceText(config);
+  }
```
Comment (kezz) [inline api/src/main/java/net/kyori/adventure/text/ScopedComponent.java]: These are incorrect as they could return components of a different type

**Review by kezz — DISMISSED** [review]
